# Question

This code snippet makes a fetch to get the first todo item from the JSON placeholder API. Or at least it tries to.

What is wrong with this code?

Describe how async/await helps us avoid this mistake.

```js
fetch("https://jsonplaceholder.typicode.com/todos/1")
  .then((response) => {
    if (!response.ok) throw new Error("Fetch failed!");
    response.json();
  })
  .then((json) => console.log(json))
  .catch((err) => console.log(err));
```

You can run this code of course, but try not to! Try to figure out the issue on your own.

# Answer

This issue with this code is that the first `.then`'s callback function does not return a value. The first `.then` will return a promise with the resolve value of `undefined` (since that is what the callback ultimately evaluates to) for the next `.then` to use and ultimately the callback function will log `undefined` to the console with `console.log(json)`

In order to make the code run how it was intended to while still using `.then`/`.catch`, this is how it would have to look:

```js
fetch("https://jsonplaceholder.typicode.com/todos/1")
  .then((response) => {
    if (!response.ok) throw new Error("Fetch failed!");
    return response.json();
    //  ^^^^^^ this return will now allow the json to be passed onto the next .then
  })
  .then((json) => console.log(json))
  .catch((err) => console.log(err));
```

# Teacher Feedback
